### ISSUE TITLE
populating .id doesn't work with lean mongoose streams

### ISSUE THREAD

**Issue by bobzoller** [goodeggs/mongoose-lean#1]

**Comment by keytronic** [comment]
+1

**Comment by bobzoller** [comment]
truth be told we don't use mongoose-lean any more.  the fact that it applies globally causes problems when using other modules that expect mongoose to return fat models by default.  This limits its usefulness for us.

I'm happy to accept a PR or transfer ownership in some way, but I'm going to close this issue as I don't plan on fixing it.
